# MA0054 - Embed caught exception as inner exception

You should include the original exception when you throw an exception in a `catch` block. This way you don't hide the original exception and this is easier to debug.

````csharp
try
{

}
catch(Exception ex)
{
    throw new Exception("Sample"); // Non compliant
    throw new Exception("Sample", ex); // compliant
}
````