# MA0072 - Do not throw from a finally block

Throwing an exception from a `finally` block may hide an exception thrown from the `try` or `catch` block.

````c#
try
{
    // The parent method won't be able to catch this exception
    throw new Exception("Original Exception");
}
finally
{
    // The parent method will only get this exception
    throw new Exception("Finally Exception");
}
````
