# MA0054 - Embed the caught exception as innerException

You should include the original exception when throwing a new exception from a `catch` block. Providing the original exception could make it easier to debug.

````csharp
try
{

}
catch(Exception ex)
{
    throw new Exception("Sample"); // Non compliant
    throw new Exception("Sample", ex); // compliant
}
````
